server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: social-media-site

# logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

# debug: true